# Generated by Django 5.2 on 2025-05-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_telegram_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(blank=True, max_length=16, verbose_name='Is Bot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_language',
            field=models.CharField(blank=True, max_length=16, verbose_name='Language'),
        ),
    ]
