# Generated by Django 5.2 on 2025-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_bot_alter_user_telegram_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(max_length=16, verbose_name='Is Bot'),
        ),
    ]
