# Generated by Django 5.2 on 2025-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(blank=True, max_length=16, null=True, verbose_name='Is Bot'),
        ),
    ]
