# Generated by Django 5.2 on 2025-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_latitude_center_user_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='You can describe yourself here and add contacts.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_language',
            field=models.CharField(blank=True, default='en', max_length=16, verbose_name='Language'),
        ),
    ]
