# Generated by Django 5.2 on 2025-07-07 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_description_alter_user_telegram_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialisation',
            field=models.TextField(blank=True, help_text='What is your superpower? What do you do best?', max_length=40, null=True, verbose_name='Specialisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='You can describe yourself and add contacts here.', max_length=700, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude center of the map'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude center of the map'),
        ),
    ]
